Intro:
  Title:
    Goals for 2024
  Desc:
    This is my first year with FreeAgent and it’s a long time since I used wither Ruby or Rails
  Bullets:
   - Understand the domain of Freeagent and Radar
   - Improve my Ruby proficiency to the point where I can make meaningful code reviews and write appropriate tests
